//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: ulxlc Created :
// Initializer: ulxlc.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "ulxlcFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Ulxlc_Init(Tcl_Interp* tclInterp);
extern "C" int Ulxlc_SafeInit(Tcl_Interp* tclInterp);

int Ulxlc_Init(Tcl_Interp* tclInterp)
{
        return Ulxlc_SafeInit(tclInterp);
}

int Ulxlc_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "ulxlc";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createulxlcFunctionMap();
        XSModelFunction::updateComponentList
              ("/home/nk7g14/Desktop/gitbox/ulx_pop/ulxlc_code_v0.1/lmodel_ulxlc.dat");
        return TCL_OK;

}

