//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: ulxlc
// Function body: ulxlcFunctionMap.cxx

#include    "ulxlcFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>

void 
createulxlcFunctionMap()
{


	XSFunctionMap["ulxlc"]    = new XSCall<xsccCall>(ulxlcmodxspec);

}
